### ISSUE TITLE
Error Object.noSuchMethod when Tried calling: []("login") or Tried calling: []("register")

### ISSUE THREAD

**Issue by bctechjsc** [vineeshvk/chat-app-flutter#7]
Hello,
When i run this project, an error occured:
<img width="937" alt="Screen Shot 2020-06-26 at 22 06 44" src="https://user-images.githubusercontent.com/61673430/85872105-7ff93680-b7f9-11ea-82a8-a75b652b3378.png">

How can I fix it?

Thanks you!

**Comment by vineeshvk** [comment]
Hi,

This is because the data is null. To find the error that's causing it we can use the `onError` property in `MutationOptions()` like this

```
MutationOptions(
        onError: (error) {
          print("client => ${error.clientException}");
          print("graphql => ${error.graphqlErrors}");
        },
       onComplete:.....
```

**Comment by bctechjsc** [comment]
Hi, thank for your reply. I need to check my chat server (I have deployed on myself server)

Thanks you!

**Comment by AdamLBS** [comment]
> Hi, thank for your reply. I need to check my chat server (I have deployed on myself server)
> 
> Thanks you!

What was the problem with your chat server ? I have the same problem
